name: Pigeon Potato Tester

on:
  push:
    branches: [ root ]
  pull_request:
    branches: [ root ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: make install
      run: make install
