name: Pigeon Potato Compiler Tester

on:
  push:
    branches: [ root ]
  pull_request:
    branches: [ root ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Funny message
      run: echo WOOT WOOT IT WORKS
    - name: List stuff
      run: ls
    - name: Run the compiler
      run: ./ppc help
    - name: Punk rock time
      run: ./ppc astro-zombies
    - name: clean
      run: rm ppc
    - name: List more stuff
      run: ls
