name: Pigeon Potato Compiler Tester

on:
  push:
    branches: [ root ]
  pull_request:
    branches: [ root ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Funny message
      run: echo WOOT WOOT IT WORKS
    - name: Create blank file
      run: touch newfile.c
    - name: List stuff
      run: ls
    - name: Run the compiler
      run: ./ppc newfile.c
    - name: Kill executable file
      run: rm ppc
    - name: Kill newfile.c
      run: rm newfile.c
    - name: List more stuff
      run: ls
